# Numpy

In [1]:
import numpy as np

### DataTypes & Attributes

#### Numpy's main datatype id ndarray

In [4]:
a1=np.array([1,2,3])

In [7]:
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [10]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
type(a2)

numpy.ndarray

In [23]:
print(np.shape(a1))
print(np.shape(a2))
print(np.shape(a3))

(3,)
(2, 3)
(2, 3, 3)
