# Numpy

In [1]:
import numpy as np


### DataTypes & Attributes

#### Numpy's main datatype id ndarray

In [4]:
a1=np.array([1,2,3])

In [7]:
a1

array([1, 2, 3])

In [8]:
type(a1)

numpy.ndarray

In [10]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
type(a2)

numpy.ndarray

In [24]:
np.shape(a1)

(3,)

In [25]:
np.shape(a2)

(2, 3)

In [26]:
np.shape(a3)

(2, 3, 3)

In [28]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [33]:
a1.dtype

dtype('int32')

In [34]:
a2.dtype

dtype('float64')

In [35]:
a3.dtype

dtype('int32')

In [36]:
a1.size

3

In [37]:
a2.size

6

In [38]:
a3.size

18

In [39]:
type(a1)

numpy.ndarray

In [40]:
type(a2)

numpy.ndarray

In [41]:
type(a3)

numpy.ndarray

### Create a DataFrame from a Numpy array