# Numpy

In [96]:
import numpy as np
import pandas as pd

### DataTypes & Attributes

#### Numpy's main datatype id ndarray

In [97]:
a1=np.array([1,2,3])

In [98]:
a1

array([1, 2, 3])

In [99]:
type(a1)

numpy.ndarray

### 2d array
#### &
### 3d array

In [100]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [101]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [102]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [103]:
type(a2)

numpy.ndarray

In [104]:
np.shape(a1)

(3,)

In [105]:
np.shape(a2)

(2, 3)

In [106]:
np.shape(a3)

(2, 3, 3)

In [107]:
a1

array([1, 2, 3])

In [108]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [109]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ndim represents the number of dimensions (axes) of the ndarray

In [110]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [111]:
a1.dtype

dtype('int32')

In [112]:
a2.dtype

dtype('float64')

In [113]:
a3.dtype

dtype('int32')

### To check the size 

In [114]:
a1.size

3

In [115]:
a2.size

6

In [116]:
a3.size

18

In [117]:
type(a1)

numpy.ndarray

In [118]:
type(a2)

numpy.ndarray

In [119]:
type(a3)

numpy.ndarray

### Create a DataFrame from a Numpy array

In [120]:
df=pd.DataFrame(a1)

In [121]:
df

0
0  1
1  2
2  3

In [122]:
df=pd.DataFrame(a2)

In [123]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [124]:
df=pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(2, 3, 3)

### Creating Arrays

In [125]:
sample_array=np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [126]:
sample_array.dtype

dtype('int32')

### ones

In [127]:
ones=np.ones((2, 3))

In [128]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [129]:
ones.dtype

dtype('float64')

In [130]:
type(ones)

numpy.ndarray

### Zero

In [131]:
Zero = np.zeros((2, 3))

In [132]:
Zero

array([[0., 0., 0.],
       [0., 0., 0.]])

### Creating Dataset using random variable

In [133]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [134]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[3, 4, 6, 9, 6],
       [9, 4, 6, 5, 5],
       [8, 8, 7, 4, 0]])

In [135]:
random_array.size

15

In [136]:
random_array.shape

(3, 5)

In [137]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.80743113, 0.71473099, 0.56537922],
       [0.20915605, 0.02718506, 0.86442211],
       [0.43081081, 0.27324687, 0.28720886],
       [0.6027041 , 0.85761796, 0.26732108],
       [0.44241643, 0.01198787, 0.85292944]])

In [138]:
random_array_2.shape

(5, 3)

In [139]:
random_array_2.size

15

In [140]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.07077434, 0.58966444, 0.52363629],
       [0.63790318, 0.55828866, 0.33549984],
       [0.95394882, 0.69794206, 0.7642483 ],
       [0.77220823, 0.33169586, 0.46181938],
       [0.50965103, 0.03748168, 0.36762566]])

In [141]:
random_array_3.shape

(5, 3)

### Pseudo-Random numbers

#### Generates a new set or repeats pseudo-random numbers

In [147]:
np.random.seed(seed=99999)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [148]:
random_array_4.shape

(5, 3)

In [149]:
np.random.seed(7)
range_array_5 = np.random.random((5,3))
range_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [150]:
range_array_5 = np.random.random((5,3))
range_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

# 66