# Numpy

In [2]:
import numpy as np
import pandas as pd

### DataTypes & Attributes

#### Numpy's main datatype id ndarray

In [3]:
a1=np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

### 2d array
#### &
### 3d array

In [6]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
np.shape(a1)

(3,)

In [11]:
np.shape(a2)

(2, 3)

In [12]:
np.shape(a3)

(2, 3, 3)

In [13]:
a1

array([1, 2, 3])

In [14]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### ndim represents the number of dimensions (axes) of the ndarray

In [16]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [17]:
a1.dtype

dtype('int32')

In [18]:
a2.dtype

dtype('float64')

In [19]:
a3.dtype

dtype('int32')

### To check the size 

In [20]:
a1.size

3

In [21]:
a2.size

6

In [22]:
a3.size

18

In [23]:
type(a1)

numpy.ndarray

In [24]:
type(a2)

numpy.ndarray

In [25]:
type(a3)

numpy.ndarray

### Create a DataFrame from a Numpy array

In [26]:
df=pd.DataFrame(a1)

In [27]:
df

0
0  1
1  2
2  3

In [28]:
df=pd.DataFrame(a2)

In [29]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [30]:
df=pd.DataFrame(a3)

ValueError: Must pass 2-d input. shape=(2, 3, 3)

### Creating Arrays

In [31]:
sample_array=np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [32]:
sample_array.dtype

dtype('int32')